name: Build and Validate

on:
  push:
    branches: [ main ]
    tags-ignore: [ v* ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run audit
        run: cargo audit --deny warnings --deny unmaintained --deny unsound --deny yanked
